[theme]
primaryColor        = "#C8102E"
backgroundColor     = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor           = "#0D1B40"
font                = "sans serif"

[server]
headless            = true
enableCORS          = false
enableXsrfProtection = true

[browser]
gatherUsageStats    = false
